
package webservice.impl;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceImpl", targetNamespace = "http://impl.WebService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceImpl {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPosition", targetNamespace = "http://impl.WebService/", className = "webservice.impl.GetPosition")
    @ResponseWrapper(localName = "getPositionResponse", targetNamespace = "http://impl.WebService/", className = "webservice.impl.GetPositionResponse")
    @Action(input = "http://impl.WebService/WebServiceImpl/getPositionRequest", output = "http://impl.WebService/WebServiceImpl/getPositionResponse")
    public String getPosition();

}
