
package xyz.dingjiacheng.hbasewebservice.service.impl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "Exception", targetNamespace = "http://impl.service.hbaseWebService.dingjiacheng.xyz/")
public class Exception_Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private xyz.dingjiacheng.hbasewebservice.service.impl.Exception faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public Exception_Exception(String message, xyz.dingjiacheng.hbasewebservice.service.impl.Exception faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public Exception_Exception(String message, xyz.dingjiacheng.hbasewebservice.service.impl.Exception faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: xyz.dingjiacheng.hbasewebservice.service.impl.Exception
     */
    public xyz.dingjiacheng.hbasewebservice.service.impl.Exception getFaultInfo() {
        return faultInfo;
    }

}
