
package xyz.dingjiacheng.hbasewebservice.service.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceImpl", targetNamespace = "http://impl.service.hbaseWebService.dingjiacheng.xyz/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "scanOrderByDriver", targetNamespace = "http://impl.service.hbaseWebService.dingjiacheng.xyz/", className = "xyz.dingjiacheng.hbasewebservice.service.impl.ScanOrderByDriver")
    @ResponseWrapper(localName = "scanOrderByDriverResponse", targetNamespace = "http://impl.service.hbaseWebService.dingjiacheng.xyz/", className = "xyz.dingjiacheng.hbasewebservice.service.impl.ScanOrderByDriverResponse")
    @Action(input = "http://impl.service.hbaseWebService.dingjiacheng.xyz/WebServiceImpl/scanOrderByDriverRequest", output = "http://impl.service.hbaseWebService.dingjiacheng.xyz/WebServiceImpl/scanOrderByDriverResponse")
    public String scanOrderByDriver(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://impl.service.hbaseWebService.dingjiacheng.xyz/", className = "xyz.dingjiacheng.hbasewebservice.service.impl.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://impl.service.hbaseWebService.dingjiacheng.xyz/", className = "xyz.dingjiacheng.hbasewebservice.service.impl.SayHelloResponse")
    @Action(input = "http://impl.service.hbaseWebService.dingjiacheng.xyz/WebServiceImpl/sayHelloRequest", output = "http://impl.service.hbaseWebService.dingjiacheng.xyz/WebServiceImpl/sayHelloResponse")
    public String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "scanPositionByOrder", targetNamespace = "http://impl.service.hbaseWebService.dingjiacheng.xyz/", className = "xyz.dingjiacheng.hbasewebservice.service.impl.ScanPositionByOrder")
    @ResponseWrapper(localName = "scanPositionByOrderResponse", targetNamespace = "http://impl.service.hbaseWebService.dingjiacheng.xyz/", className = "xyz.dingjiacheng.hbasewebservice.service.impl.ScanPositionByOrderResponse")
    @Action(input = "http://impl.service.hbaseWebService.dingjiacheng.xyz/WebServiceImpl/scanPositionByOrderRequest", output = "http://impl.service.hbaseWebService.dingjiacheng.xyz/WebServiceImpl/scanPositionByOrderResponse")
    public String scanPositionByOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
