
package hello.examples.spyne;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Application", targetNamespace = "spyne.examples.hello")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Application {


    /**
     * 
     * @param lon
     * @param lat
     * @return
     *     returns java.lang.Double
     */
    @WebMethod(action = "myknnpre")
    @WebResult(name = "myknnpreResult", targetNamespace = "spyne.examples.hello")
    @RequestWrapper(localName = "myknnpre", targetNamespace = "spyne.examples.hello", className = "hello.examples.spyne.Myknnpre")
    @ResponseWrapper(localName = "myknnpreResponse", targetNamespace = "spyne.examples.hello", className = "hello.examples.spyne.MyknnpreResponse")
    public Double myknnpre(
        @WebParam(name = "lat", targetNamespace = "spyne.examples.hello")
        Double lat,
        @WebParam(name = "lon", targetNamespace = "spyne.examples.hello")
        Double lon);

    /**
     * 
     * @param last1
     * @param positiontype
     * @param day2
     * @param israin
     * @param day1
     * @param time
     * @return
     *     returns java.lang.Double
     */
    @WebMethod(action = "mymlppre")
    @WebResult(name = "mymlppreResult", targetNamespace = "spyne.examples.hello")
    @RequestWrapper(localName = "mymlppre", targetNamespace = "spyne.examples.hello", className = "hello.examples.spyne.Mymlppre")
    @ResponseWrapper(localName = "mymlppreResponse", targetNamespace = "spyne.examples.hello", className = "hello.examples.spyne.MymlppreResponse")
    public Double mymlppre(
        @WebParam(name = "day1", targetNamespace = "spyne.examples.hello")
        Double day1,
        @WebParam(name = "day2", targetNamespace = "spyne.examples.hello")
        Double day2,
        @WebParam(name = "last1", targetNamespace = "spyne.examples.hello")
        Double last1,
        @WebParam(name = "israin", targetNamespace = "spyne.examples.hello")
        Double israin,
        @WebParam(name = "time", targetNamespace = "spyne.examples.hello")
        Double time,
        @WebParam(name = "positiontype", targetNamespace = "spyne.examples.hello")
        Double positiontype);

}
